In [6]:
import numpy as np

In [7]:
batch_size = 5
num_of_class = 3
x = np.random.randint(0, 10, (batch_size, num_of_class))
y = np.random.randint(0, num_of_class, batch_size)

In [10]:
print(x)

[[1 8 8]
 [5 3 6]
 [8 4 6]
 [2 6 5]
 [7 2 1]]


In [11]:
print(y)

[0 1 0 0 0]


In [24]:
z = x[np.arange(batch_size), y]
print(z)
print(z.sum())

[1 3 8 2 7]
21


In [20]:
print(z)

[1 3 8 2 7]


In [16]:
x.sum(axis=1)


array([17, 14, 18, 13, 10])

In [30]:
num_classes = 10
num_examples = 2

In [31]:
y = np.array([0, 2])

In [32]:
Iy = np.eye(num_classes)[y]

In [33]:
Iy

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
    iterations = (y.size + batch - 1) // batch
    for i in range(iterations):
        X = X[i*batch:(i+1)*batch, :]
        y = y[i*batch:(i+1)*batch]
        _, num_classes = theta.shape
        Z = np.exp(X @ theta) / np.exp(X @ theta).sum(axis=1, keepdims=True)
        Iy = np.eye(num_classes)[y]
        grad = X.transpose() @ (Z - Iy)
        theta -= lr * grad / batch